In [1]:
import pandas as pd
import numpy as np

In [2]:
df_raw = pd.read_csv("ChemBL_raw.csv", delimiter=";")
df_raw.head()

,Molecule ChEMBL ID,Molecule Name,Molecule Max Phase,Molecular Weight,#RO5 Violations,AlogP,Compound Key,Smiles,Standard Type,Standard Relation,...,Document ChEMBL ID,Source ID,Source Description,Document Journal,Document Year,Cell ChEMBL ID,Properties,Action Type,Standard Text Value,Value
0,CHEMBL1084787,NaN,NaN,274.39,0.0,3.06,223,c1ccc(-c2nnc(NCN3CCCCC3)s2)cc1,IC50,'=',...,CHEMBL1155460,1,Scientific Literature,Eur J Med Chem,2010.0,NaN,NaN,NaN,NaN,54000.0
1,CHEMBL1084788,NaN,NaN,269.35,0.0,2.39,224,c1ccc(-c2cnc(NCN3CCCCC3)nn2)cc1,IC50,'=',...,CHEMBL1155460,1,Scientific Literature,Eur J Med Chem,2010.0,NaN,NaN,NaN,NaN,60000.0
2,CHEMBL1082434,NaN,NaN,351.45,0.0,4.29,228,O=C(CCC1CCN(Cc2ccccc2)CC1)c1ccc2c(c1)OCO2,IC50,'=',...,CHEMBL1155460,1,Scientific Literature,Eur J Med Chem,2010.0,NaN,NaN,NaN,NaN,30.0
3,CHEMBL1084790,NaN,NaN,361.49,0.0,4.75,231,Cc1nc2cc(C(=O)CCC3CCN(Cc4ccccc4)CC3)ccc2[nH]1,IC50,'=',...,CHEMBL1155460,1,Scientific Literature,Eur J Med Chem,2010.0,NaN,NaN,NaN,NaN,12.0
4,CHEMBL102142,NaN,NaN,385.53,0.0,2.75,234,Cc1ccc(C(=O)NC(=S)NCCOCCN(C)Cc2ccccc2)cc1,IC50,'=',...,CHEMBL1155460,1,Scientific Literature,Eur J Med Chem,2010.0,NaN,NaN,NaN,NaN,77.0

In [3]:
df_raw.columns

Index(['Molecule ChEMBL ID', 'Molecule Name', 'Molecule Max Phase',
       'Molecular Weight', '#RO5 Violations', 'AlogP', 'Compound Key',
       'Smiles', 'Standard Type', 'Standard Relation', 'Standard Value',
       'Standard Units', 'pChEMBL Value', 'Data Validity Comment', 'Comment',
       'Uo Units', 'Ligand Efficiency BEI', 'Ligand Efficiency LE',
       'Ligand Efficiency LLE', 'Ligand Efficiency SEI', 'Potential Duplicate',
       'Assay ChEMBL ID', 'Assay Description', 'Assay Type', 'BAO Format ID',
       'BAO Label', 'Assay Organism', 'Assay Tissue ChEMBL ID',
       'Assay Tissue Name', 'Assay Cell Type', 'Assay Subcellular Fraction',
       'Assay Parameters', 'Assay Variant Accession', 'Assay Variant Mutation',
       'Target ChEMBL ID', 'Target Name', 'Target Organism', 'Target Type',
       'Document ChEMBL ID', 'Source ID', 'Source Description',
       'Document Journal', 'Document Year', 'Cell ChEMBL ID', 'Properties',
       'Action Type', 'Standard Text Value', 'Value'],
      dtype='str')

In [4]:
df_select = df_raw[['Molecule ChEMBL ID', 'Smiles', 'Standard Type', 'Standard Relation', 'Standard Value',
       'Standard Units', 'pChEMBL Value', 'Assay ChEMBL ID']]
df_select.head()

,Molecule ChEMBL ID,Smiles,Standard Type,Standard Relation,Standard Value,Standard Units,pChEMBL Value,Assay ChEMBL ID
0,CHEMBL1084787,c1ccc(-c2nnc(NCN3CCCCC3)s2)cc1,IC50,'=',54000.0,nM,4.27,CHEMBL1119333
1,CHEMBL1084788,c1ccc(-c2cnc(NCN3CCCCC3)nn2)cc1,IC50,'=',60000.0,nM,4.22,CHEMBL1119333
2,CHEMBL1082434,O=C(CCC1CCN(Cc2ccccc2)CC1)c1ccc2c(c1)OCO2,IC50,'=',30.0,nM,7.52,CHEMBL1119333
3,CHEMBL1084790,Cc1nc2cc(C(=O)CCC3CCN(Cc4ccccc4)CC3)ccc2[nH]1,IC50,'=',12.0,nM,7.92,CHEMBL1119333
4,CHEMBL102142,Cc1ccc(C(=O)NC(=S)NCCOCCN(C)Cc2ccccc2)cc1,IC50,'=',77.0,nM,7.11,CHEMBL1119333

In [5]:
new_names = ["molecule_chembl_id", "canonical_smiles", "standard_type", "standard_relation", "standard_value", "standard_units", "pchembl_value", "assay_chembl_id"]
df_select.columns = new_names
df_select.head()

,molecule_chembl_id,canonical_smiles,standard_type,standard_relation,standard_value,standard_units,pchembl_value,assay_chembl_id
0,CHEMBL1084787,c1ccc(-c2nnc(NCN3CCCCC3)s2)cc1,IC50,'=',54000.0,nM,4.27,CHEMBL1119333
1,CHEMBL1084788,c1ccc(-c2cnc(NCN3CCCCC3)nn2)cc1,IC50,'=',60000.0,nM,4.22,CHEMBL1119333
2,CHEMBL1082434,O=C(CCC1CCN(Cc2ccccc2)CC1)c1ccc2c(c1)OCO2,IC50,'=',30.0,nM,7.52,CHEMBL1119333
3,CHEMBL1084790,Cc1nc2cc(C(=O)CCC3CCN(Cc4ccccc4)CC3)ccc2[nH]1,IC50,'=',12.0,nM,7.92,CHEMBL1119333
4,CHEMBL102142,Cc1ccc(C(=O)NC(=S)NCCOCCN(C)Cc2ccccc2)cc1,IC50,'=',77.0,nM,7.11,CHEMBL1119333

In [6]:
df_select.to_csv("ache_activities.csv", index=False)

In [7]:
df_select.isna().any()

molecule_chembl_id    False
canonical_smiles       True
standard_type         False
standard_relation     False
standard_value        False
standard_units        False
pchembl_value         False
assay_chembl_id       False
dtype: bool

In [8]:
df_sample = df_select.sample(n=10)
df_sample

,molecule_chembl_id,canonical_smiles,standard_type,standard_relation,standard_value,standard_units,pchembl_value,assay_chembl_id
416,CHEMBL134154,COc1cccc2nc3c(c(N)c12)CCCO3,IC50,'=',606.0,nM,6.22,CHEMBL644109
6027,CHEMBL5188111,CCCCCCCNC(=O)Oc1ccc(Cc2nc3cc(C(=O)N(CC)CC)ccc3...,IC50,'=',2148.0,nM,5.67,CHEMBL5111262
76,CHEMBL4518938,Fc1ccc(/C=N/C2CCN(Cc3ccccc3)CC2)cc1,IC50,'=',2900.0,nM,5.54,CHEMBL4433401
1013,CHEMBL92663,NC(=O)c1ccc2c(CCC3CCN(Cc4ccccc4)CC3)noc2c1,IC50,'=',8.8,nM,8.06,CHEMBL1119333
474,CHEMBL292314,Nc1c2c(nc3cc(Cl)ccc13)CCCC2,IC50,'=',10.0,nM,8.00,CHEMBL638445
2706,CHEMBL32768,CCCCCCCCOC[n+]1ccn(C)c1/C=N/O.[Cl-],IC50,'=',9500.0,nM,5.02,CHEMBL644116
3320,CHEMBL4166257,CNC(=O)c1cc2c(OC(=O)N(C)C)cccc2[n+](Cc2ccccc2)...,IC50,'=',1160.0,nM,5.94,CHEMBL4155648
1250,CHEMBL3220807,C[C@H]1C[C@@]23CC[C@H]4[C@@](C)(CCC[C@@]4(C)C(...,IC50,'=',34000.0,nM,4.47,CHEMBL3225749
5207,CHEMBL575167,C#CCCCCCCN1CCc2cc(OC)c(OC)cc2C1c1ccc([N+](=O)[...,IC50,'=',2920.0,nM,5.54,CHEMBL1041236
1534,CHEMBL81,O=C(c1ccc(OCCN2CCCCC2)cc1)c1c(-c2ccc(O)cc2)sc2...,IC50,'=',400.0,nM,6.40,CHEMBL1909212